.gitignore
README.md
backtesting/backtesting.py
backtesting/strategy.py
config.json
data/datamodule.py
data/tradingmodule.py
main.py
main_controller.py
models/backtest-result.py
models/ohlcv.py
models/pair-stat.py
models/trade.py
requirements.txt

First version including following features:
- CCXT as dataprovider
- Support for all CCXT provided exchanges
- Compound mode
- Overall statistics / performance
- Multi coin
- Backtesting in a set time range
- Clear config file
- README running instructions

[Feat] First rough version

---

.github/workflows/Docs Deployment Pipeline.yml

Pipeline for the documentation via MkDocs.

Create Docs Deployment Pipeline.yml

---

data/tradingmodule.py

updated total price calculation

---

data/datamodule.py

Now allows for the use of pre-generated historical data rather than always download the data
Builds upon #27

[Hotfix]  Fix naming error

---

backtesting/backtesting.py
data/tradingmodule.py

Fixes #16 
Edit: Merge with development to include #37

[Fix] Fix the way max_seen_drawdown is calculated in backtesting

---

config/__init__.py
config/validations.py
data/datamodule.py

Fixes #10
All SystemExit were replaced by proper throw methode. 
raise SystemExit -> raise FileNotFoundError("[ERROR] Backtesting datafile was not found.")
None
n/a

Proper error handling application wide #10

---

.github/workflows/deploy_to_stable.yml

[Release] #patch

---

README.md

[Fix] Readme edited documentation link

---

README.md

Fixes #102 
* Changed some small typos in the README.md file
N/A
N/A
N/A
N/A
N/A

Small Readme.md updates

---

backtesting/backtesting.py
backtesting/results.py
config.json
data/tradingmodule.py
main.py

close #63 Added and calculated the fee_amount and the total_fee_ammount based on the fee imposed by the client. In case the fee is invalid we will use a default fee. Added a fee verification function. Print the total_fee_amount in the BackTesting file.

Solved issue 63

---

data/tradingmodule.py
makefile

[Fix] Typo fix

---

backtesting/backtesting.py
backtesting/strategy.py
config.json
data/datamodule.py
data/tradingmodule.py
docs/strategyexamples.md
mkdocs.yml

Fixes #106 
- Changes for https://docs.dematrading.ai/strategyexamples/ page
- Additions to mkdocs.yml for fancy displaying
Read the changes + https://squidfunk.github.io/mkdocs-material/reference/admonitions/ for the additions to mkdocs.yml.

[Docs] Additions for beta

---

makingmoney.md

Making money.md

---

docs/quickstart.md
docs/strategyexamples.md

[hotfix] hotfix for docs

---

docs/index.md

[Hotfix] hotfix

---

config/validations.py
data/tradingmodule.py

Fixes #108
Fee validation was done in the tradingmodule, while there is a dedicated file for config validations. Moved it there.

Placed the fee validation in the proper location (config/validations.py)

---

backtesting/backtesting.py
backtesting/results.py
backtesting/strategy.py
config/currencies.py
config/load_strategy.py
data/datamodule.py
data/tradingmodule.py
main.py
main_controller.py
models/trade.py
requirements.txt
strategies/my_strategy.py
test/test.py
test/test_test.py
utils.py

Fixes #104
Fixes #122
Fixes #123 
* Significantly increased backtesting time
* Changed fee calculation to the correct implementation (was changed incorrectly)
* Population of indicators and signals is only executed once
* Population is moved from tradingmodule.py to backtesting.py
* Changed dataframe lookups to dictionary lookups
* Functions in strategy class now only receives the whole dataframe (not: passed_ticks + current_tick)
* .json files are now stored and retrieved using fastjson instead of the standard json library
* Added structure to the imports in the beginning of each file
* Fixed incorrect data downloading bug when 'backtesting-till-now' is true
* Changed method for converting dataframe to json and vice versa
* Dataframe is NOT using datetime as index anymore (changed to …

[Feat] Backtest optimisation

---

backtesting/results.py
backtesting/strategy.py
config.example.json
config.json
config/validations.py
data/datamodule.py
data/tradingmodule.py
strategies/my_strategy.py

1. Feedback to the end-user is more clear now
2. Adjusted base settings for quick testing
3. Added list of possible indicators
4. RSI missing time-period
5. Revised copyright part of backtesting results
6. Feature requests for documentation, see https://github.com/dema-trading-ai/wiki/issues

[Feat] Adjustments based on feedback

---

config.json

[Fix] Fix fee

---

data/datamodule.py

Fixes errors occuring in datamodule.

[Hotfix] Hotfix for datamodule #patch

---

backtesting/results.py
utils.py

Changed:
- Added version to backtest results
- Version manually configurable in utils.py
- Included changing version in Engine Release Protocol

[Feat] Added version to backtest result

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_stable.yml
README.md

PR for creating and pushing a dockerimage on new pushes to the development branch.

[Feat] created development release pipeline

---

.github/pull_request_template.md

Fixes #150
A section has been added to the PR template file that outlines assumptions made/things to be added to the wiki
N/A
N/A
N/A
N/A
N/A

[adds] - wiki/assumptions section to PR template

---

makefile

Replaced 4 spaced by 1 tab to fix error.

[Hotfix] fixed makefile indent mistake

---

.github/workflows/deploy_to_dev.yml

Fixed an error in workflow dependencies. The workflow file contained a non-existing dependency.
2 lines in Github workflow
N/A
N/A
N/A
N/A
N/A

[Fix] workflow error fix

---

config/qtpylib_methods.py
strategies/my_strategy.py

Fixes #125 
A 'light' version of qtpylib has been added. This means that only the indicator functions are added, such as `crossed_below`. 
```python
qtpylib.crossed_above(dataframe['rsi'], 50)
```
Will be true if rsi was below 50 the previous candle, and crossed above 50 in the current candle.
N/A
N/A
N/A
N/A

Feature - QTpylib implementation

---

data/tradingmodule.py

Fixes #163 
Added a check to stop the engine from crashing if it tried to open a trade when none was available as per the config file.
From:
To:
N/A
This is an exception handling in and of itself
Doesn't look super pretty, might be worth thinking about how to implement in a more user-friendly way in the future.

[Fix] No open trades bug

---

utils.py

Hotfix for wrong version in utils.py

[Hotfix] #patch

---

backtesting/backtesting.py
backtesting/results.py
config.json
data/datamodule.py
data/tradingmodule.py
models/trade.py
utils.py

Fixes #170 
Fixes #61 
* Fixed wrong avg trade duration
* Changed the way 'spend_amount' (trade value for new trade) is defined. This will prevent the portfolio from becomming unbalanced (e.g. 1/4 budget in one trade and 3/4 budget in another trade)
* Old: (1 / available_spaces) * budget
* New: (1 / amount_of_pairs) * budget
* Fixed incorrect drawdown calculations for 'backtest results'
* Fixed incorrect drawdown calculations for 'per coin insights'
* Changed profit percentage columns for 'per coin insights'
* Now consists of 'avg profit', 'cum profit' and 'total profit'
* Profit percentages only include closed trades and not open trades (these are shown in 'left open trades' table)
* Renamed metrics in results table:
* Max drawdown bad trade train -> most consecutive losses
* Most …

[Fix] Correct drawdown calculation

---

backtesting/backtesting.py
config.json
config/__init__.py
data/datamodule.py
data/tradingmodule.py
strategies/my_strategy_advanced.py

N/A
* Fixed incorrect use of downloaded .json data
* Updated dynamic stoploss warning
* Changed plots argument to boolean
* Removed if statement from advanced_strategy
N/A
N/A
N/A
N/A
N/A

[Fix] Minor bug fixes

---

utils.py

[Feat] last preps for new release v0.5 #minor

---

utils.py

Update version to 0.6.0

---

test/test_stats.py
utils.py

N/A
* Added more drawdown tests
N/A
N/A
N/A
N/A
N/A

[Feat] Added drawdown tests

---

test/stats/stats_test_utils.py

[Fix] Pytest errors and warnings

---

backtesting/results.py
modules/output/__init__.py
strategies/indicator_sample.py

Fixes #215 
Fixed Typo, commented presentation of worst trade

Feat/remove broken stats: "Worst trade", "Best trade" 

---

utils.py

remove unnecessary comments

---

cli/prepare_workspace.py

Fixes #235 
Changed owner of created files to `1000`

Set owner of files create in `init` command #patch

---

modules/output/__init__.py

Removes coin insights from results overview. Needs redesign.
Coin insights need to be redesigned in the near future.

Remove coin insights from result overview until it is redesigned

---

utils.py

Updates utils.py version for next release

Release update version nr

---

modules/setup/config/__init__.py

Fixes #253 
#254 Made the config flag mandatory. This PR adds a default fallback when no config location is specified as argument
N/A
N/A
N/A
N/A
N/A
N/A
N/A

Config flag no longer mandatory

---

main.py
main_controller.py
modules/setup/__init__.py
modules/setup/config/__init__.py
modules/setup/config/cctx_adapter.py
modules/setup/datamodule.py
modules/stats/tradingmodule.py

Fixes #272 
Made fetching of ohlcv concurrent

Made downloading of ohlcv concurrent

---

README.md
makefile

No delay in logging while using docker - see where the program is at any point in time!

Show real-time print statements when running with docker make command

---

.github/workflows/build_executables_windows.yml
cli/arg_parse.py
main.py
modules/output/__init__.py
modules/setup/config/__init__.py
modules/setup/datamodule.py

Add utf8-encoding to open

---

modules/output/results.py
modules/setup/config/__init__.py

Fixes #
* Fixed some small CLI bugs related to date formatting

[Fix] CLI bugs

---

modules/output/plots.py

Changes the default plot save location to their own folder, instead of together with the cached binance data.

save plots in their own directory

---

Dockerfile
cli/arg_parse.py
cli/prepare_workspace.py
utils/utils.py

New `<dir>` argument to init command fails to write to correct directory. When running in docker it now resolves relative to `output`

Added output workspace

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_stable.yml

Add docker cache

---

cli/print_utils.py
modules/output/results.py

Fixes #
* Made the consoles of the Rich package global
* Fixed incorrect print cut-off

Global rich console

---

cli/checks/latest_version.py

Remove reason from version_check

Remove reason when version check fails

---

cli/print_utils.py
main.py
main_controller.py
modules/algo/backtesting.py
modules/setup/__init__.py
modules/setup/config/__init__.py
modules/setup/datamodule.py
modules/stats/stats_config.py
utils/utils.py

Moved loading of btc_market change to Datamodule. Added debug flag

Refactor load market change to datamodule

---

modules/setup/datamodule.py

Fixes #
Bug when downloading extra candles
Convert all index to str again before locating them.
Atm old ones were int & new added str

Fix small bug while downloading extra candles

---

modules/setup/__init__.py
modules/setup/datamodule.py

Fixes #
A function has been changed which caused an error when BTC was not in the pairlist. Fixed now

Fixes data download bug

---

modules/stats/tradingmodule.py

* Changed spend amount allocation
* Throws warning if amount of whitelisted pairs is bigger than the amount of max open trades

[Hotfix] Changed spend amount allocation

---

.github/workflows/deploy_to_dev.yml
.github/workflows/deploy_to_stable.yml

Add environment specifier to pipeline runs to allow them to access environment scoped credentials.

Add environment to pipelines

---

modules/algo/backtesting.py

changing the OHLCV data in the strategy file results in an error and exit of the engine.

[Feat] OHLCV Data unchangable

---

cli/checks/latest_version.py
utils/utils.py

Adds dynamic update notification for running in docker/executables/git

Update notification multiplatform

---

modules/output/plots.py
modules/output/plots_per_coin.py
modules/stats/stats.py

Fixes the bug that caused close prices in the plot to be set to close prices of the candle, instead of the actual trade close price.

Change plot buy and sell points to actual trade buy and sell points

---

config.json

sets default tearsheet to false in config, to increase backtesting speed

set default tearsheet to false

---

cli/checks/latest_version.py
utils/utils.py

Changes the update message to a generic one pointing to the docs

Updated update message

---

modules/output/__init__.py
modules/stats/trade.py

Added close.trade to dict for json export

Add close price of trade to the trade log export

---

modules/setup/config/__init__.py

* Fixes backtesting-till-now bugs

Fixed backtesting-till-now

---

modules/public/technical_indicators.py
resources/setup/strategies/indicator_sample.py

Fixes #
Adds Heikin Ashi candle dataframe to the technical indicators sample

heikin dataframe sample

---

modules/output/__init__.py
modules/output/equity_plot.py
modules/stats/get_stats_config.py
modules/stats/stats_config.py
modules/stats/tradingmodule.py
test/stats/stats_test_utils.py

Adds bot name (and dematrading.ai) to equity plot.
Result:

Add bot name to equity plot

---

modules/output/equity_plot.py

Fix a small bug where a math error would pop up when running out of capital halfway through a backtest due to trying to feed a negative value into a log function.

Fix small math bug

---

resources/setup/config.json

Updates the executable standard config file to reflect the changes in the main config file.

Realign executable config and main config file

---

cli/checks/latest_version.py
requirements.txt

Some instances of Python will not have the certificates installed. This adds a module that takes care of that, without the user having to manually install certificates.

Fix "Error while checking version"

---

.github/pull_request_template.md
README.md
installation_helpers/install-windows-development.ps1
installation_helpers/install-windows.ps1
modules/setup/config/__init__.py

Changes all instances in text of 'engine' to 'Engine'.

Engine is case sensitive

---

utils/utils.py

Updates utils.py to next version

Version update

---

modules/output/results.py
modules/public/trading_stats.py
modules/stats/metrics/trades.py
modules/stats/stats.py
test/stats/test_main_results.py

Add the median trade profit metric to the trade table

Add median trade profit

---

test/stats/test_drawdowns.py
test/stats/test_main_results.py
test/stats/test_open_trades.py
test/stats/test_roi_stoploss.py
test/utils/signal_frame.py

Adds the tests of profitable weeks and outperforming market weeks. Cleaned up the test code a bit.

Profitable & Outperforming weeks tests

---

cli/print_utils.py
main_controller.py

Doesn't print warnings when running the hyperoptimalization, but still prints info and errors if applicable.

Hyperopt - no warnings

---

modules/output/results.py

Adds an adapting currency symbol to the median trade

[Fix] Add auto currency symbol to median trade

---

config.json
modules/setup/__init__.py
modules/setup/config/__init__.py
modules/setup/config/validations.py
resources/config-defaults.json
test/stats/test_coin_insights.py
test/stats/test_drawdowns.py
test/stats/test_main_results.py
test/stats/test_open_trades.py
test/stats/test_roi_stoploss.py

Removes the currency from the pairs list in the config file. Autoupdates the config file if it detects the currency in the pair list.

[Feat] Remove currency from pairs

---

modules/setup/datamodule.py

Before this PR, if you needed to download a lot of candles at the same time, you'd get an error (RuntimeError: throttle queue is over maxCapacity). This was because we overloaded the cctx throttle queue with too big requests. You can reproduce this error by using the following config settings: (be sure to remove your feather files in data/backtesting-data/binance beforehand, otherwise you might not have to download the data and the error won't show)
"timeframe": "5m",
"backtesting-from": "2019-01-01",
"backtesting-to": "2022-01-01",
"pairs": ["BTC", "LTC", "ETH", "ADA"],
This PR fixes that by firing off the requests in chunks of 200, instead of all at once. This has an impact on the performance speed, but only barely (less than half a second added on the default config & strategy …

[Fix] Don't jam the throttle queue

---

README.md

Changes the Discord link in the README

[Fix] Change discord link

---

utils/utils.py

[Feat] Update version in utils.py

---

modules/output/results.py
test/stats/test_coin_insights.py

Refactors some tests in test_coin_insights to remove redundancies Also fixes a small unrelated bug found during testing.

[ENG-35] Refactor test for coin performance

---

modules/output/results.py
utils/utils.py

Makes sure daily candles can be used, both in the regular config and in additional pairs.

[ENG-84] Add daily timeframe support

---

resources/config-defaults.json
resources/setup/config.json

The development config file in the base folder had deviated slightly and the default config file and executable config file hadn't been updated properly. This PR fixes that.

[ENG-94] Realign executable and default config file with development config file

---

.github/workflows/build_executable_linux.yml
installation_helpers/install_talib.sh

Add a yaml instructing GitHub Actions to build a linux-compatible executable and deploy it on AWS

[ENG-36] Add linux executable support

---

test/setup/config/test_default_files.py

Some elements of the default configs turned out not to be tested. This PR fixes that.

[ENG-96] Fix default config tests

---

config.json
modules/output/__init__.py
modules/setup/config/__init__.py
modules/setup/config/validations.py
resources/config-defaults.json
resources/setup/config.json
resources/specification.json
test/setup/config/test_default_files.py
test/stats/stats_test_utils.py

Before, the plotting behaviour could not be influenced by using a cli parameter. This PR fixes that.

[ENG-95] Disable plots via cli parameter
