dema-trading-ai/engine

Dockerfile
After this change docker will only reinstall dependencies from `requirements.txt` whenever this file is changed. Before, it would run it every time, which results in extra build time
=> Better pip caching when building images 

backtesting/backtesting.py, data/tradingmodule.py, utils.py
Fixes #48
Checked calculation; ran and recalculated everything
Removed redundant sell reasons dict (from generate coin result)
renamed var for avg_profit_prct
moved helper functions to utils
As it was, the sell seasons dict was first calculated and then recalculated in exacly the same format.
None
n/a
=> cleanup calculation

backtesting/strategy.py, data/tradingmodule.py, models/trade.py
Fixes #75
You now have the option to change the stoploss per every tick by overriding the `stoploss` method on `Strategy`. If not provided, use configured stoploss value. This stoploss is also saved in every trade. 
I also changed some of the variable names and docstrings in `Strategy`. For instance the candle and indicator dataframes were both named `dataframe: DataFrame`. Ambiguous, and the type annotation already stated that is a `DataFrame`.
=> Added ability to dynamically change the stoploss in a strategy

data/datamodule.py
Fixes #84
In `Datamodule` I added a method that checks for missing ticks. If more than zero prints a warning. I did not find missing data, either by looking at the data or by this method, so it does not show anything right now. Warning what exact dates/ticks are missing seems too much, maybe when after adding a `--verbose` option in the cli. 
`[WARNING] Pair 'USDT/BITC' contains 4 missing ticks`
=> Adding a check for missing ticks

backtesting/backtesting.py, backtesting/strategy.py, config/cli.py, data/datamodule.py, strategies/indicator_sample.py, strategies/my_strategy.py
Fixes #23 
* Since our engine is not live trading anymore, the if statement in the strategy class (```if len(dataframe) > self.min_candles:```)
has become useless. This is useless because we now populate our indicators once based on the whole dataframe, which will always pass this if statement. This is removed.
* Since generate_indicators will use certain timeframes to populate indicators, it will create NaN values until it reached the configured timeframe. If these values are used in the .loc function for generating buy or sell signals, it will always fail. Therefore, incorrect buy signals will never be generated and the 'startup time' is automatically defined.
N/A
N/A
N/A
N/A
N/A
=> [Feat] Proper startup time

data/tradingmodule.py, data/tradingmodule_config.py, modules/setup/config/__init__.py, test/test_stats.py, utils.py
Fixes the way stoploss is fetched from the config style, and alters the way roi is calculated.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> [Fix] Correct stoploss, roi #patch

data/tradingmodule.py, models/trade.py, modules/output/__init__.py, modules/stats/stats.py, modules/stats/trading_stats.py, test/stats/stats_test_utils.py, test/stats/test_roi_stoploss.py, test/stats/test_stats.py, utils.py
Fixed a bug that was triggered when both ROI and stoploss values are reached in one candle
Add to the wiki:
Explanation about ROI & Stoploss warning and what to do to avoid it
=> [Fix] Stoploss and ROI both reached bug, fixed

modules/output/plots.py
Fixes a bug that zooms the main plot out due to zero values in the buy & sell signals, instead of nan values
=> Remove graph zoom out due to buy signals with value zero

modules/setup/config/currencies.py, modules/setup/config/specification.json
Adds BTC and ETH as possible base currencies. Will show "BTC" or "ETH" respectively in results overview instead of currency symbol.
=> add BTC and ETH as currencies

cli/arg_parse.py
Makes it once again possible to run the engine straight from python while using a python3 version that is not python 3.9
=> remove unneccesary @cache

.github/workflows/PR-Push-test.yml
Since both `development` & `main` are protected, there should be no possibility for lint errors to sneak in. Not running on every push saves us some runner resources
=> Removed running on push to save some runner resources

modules/output/results.py
* Changes color of 'performance' and 'trade info' table to white
Fixes unreadable trade info results in Windows Powershell:
=> Fix results color

modules/output/__init__.py
* Fixed bug in trades log where trades opened on the same timestamp where not all logged (since 'opened at' was used as key')
* Fixed tearsheet bug where the last trade entry was nog included
=> Fixed trades log and tearsheet bugs

backtest_runner.py, config.json, modules/output/__init__.py, modules/setup/config/__init__.py, modules/stats/get_stats_config.py, modules/stats/stats_config.py, resources/specification.json, test/stats/stats_test_utils.py
Fixes #
When the `export_result` setting is set through the config file or CLI, the main results are written to a json file in the `data/backtesting-data/` folder.
=> added json export of main results

config.example.json, config.json, modules/algo/backtesting.py, modules/output/results.py, modules/stats/stats.py, modules/stats/trade.py, modules/stats/tradingmodule_config.py, resources/specification.json, test/stats/stats_test_utils.py
Renaming of the 'standard' stoploss value - it is now called 'static'. Checks have been built in for backwards compatability - if someone now uses 'standard', they will get a warning and the stoploss type will be automatically set on 'static'.
=> change standard stoploss to static stoploss

config.json, modules/stats/metrics/winning_weeks.py
The winning draw losing weeks metric was not the same for the general overview, and coin insight. This PR fixes that, by calculating the market ratio in the same way as the profit ratio is calculated, and removing rounding errors. It also broadens the scope of a 'draw' from 'exactly the same' to 'in a 0.001 range'.
=> Fix for the 'winning draw losing weeks' bug

modules/setup/config/__init__.py
Adds a proper error message that displays when the date is not formatted correctly (so not in a YYYY-MM-DD format), and then exits.
=> Add "Date incorrectly formatted" error message

modules/output/results.py, modules/stats/stats.py
Addition of "winning and losing trades" metric to coin signals.
=> Add Winning and Losing trades metric to coin insight

modules/stats/metrics/winning_weeks.py
The equity plot sometimes doesn't fill properly to zero, instead filling to the trendline. This was because of an extra timestep added (for the calculation of the fees) which was saved permanently, instead of added only for the necessary calculations. This PR fixes that.
=> Fix equity plot fill error

modules/setup/config/__init__.py
When setting 'backtesting till now' to True, the formatting of the "Gathering data from x to y" message was off. This PR fixes that.
=> Properly format "Gathering to" message

modules/stats/tradingmodule.py
Only show "Error Budget Low" warning when max open trades is not yet reached.
=> Fix Error Budget Low appearing when max open trades is reached

modules/stats/drawdown/for_portfolio.py, test/stats/test_drawdowns.py
Fixes the error that shows up when your drawdown period starts at the first timestep. The 'backtesting from' was set to the copied first row, that's used for fee purposes, but has timestamp 0. This PR fixes that, and also fixes the tests that were not correct due to this bug.
=> Fix Drawdown period from start not shown

modules/setup/config/validations.py
Change a type return from tuple[float, type] to Tuple[float, type] as it triggers errors in Python < 3.9
=> Change tuple to Tuple from typing

modules/output/equity_plot.py
Equity plots are saved using the strategy name rather than 'equityplot'.
=> Add ability for equity plots be exported with the strategy name

modules/setup/config/__init__.py
Gracefully fails when trying to run engine from the wrong folder, and suggests the user to look at the documentation for how to correctly run the engine.
=> Fail gracefully when trying to run engine from wrong folder

modules/setup/datamodule.py
Fixes the following error that occurs on some random timerange intervals
```
Traceback (most recent call last):
File "/usr/src/engine/main.py", line 46, in <module>
main()
File "/usr/src/engine/main.py", line 25, in main
execute_for_args({
File "/usr/src/engine/cli/arg_parse.py", line 41, in execute_for_args
args.func(args)
File "/usr/src/engine/main.py", line 34, in run_engine
asyncio.get_event_loop().run_until_complete(controller.run(args))
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/src/engine/main_controller.py", line 25, in run
runner.run_outputted_backtest()
File "/usr/src/engine/backtest_runner.py", line 35, in run_outputted_backtest
stats = self.run_backtest()
File "/usr/src/engine/backtest_runner.py", …
```
=> Fixes "can't compare identically-labeled series" error

modules/output/__init__.py
Fixes the trade log generation message in the backtesting output to match the new filename structure introduced in #434.
Now you'll see:
`[INFO] Logging trades to data/backtesting-data/trades_log_MyStrategy.json...`
=> fix trade log message

modules/output/__init__.py, modules/stats/trade.py, modules/stats/tradingmodule.py
Adds the 'fee percentage' to the trade log header, and adds open trade fee, close trade fee, and total fee paid to the trade log on a per-trade level.
=> Add trade fee to trade logs

modules/output/__init__.py
Removes the old trade log, if it exists, in order to make it less confusing for our users.
This block of code can be removed in future versions, when we're reasonably sure that the old trade logs are no longer existent on our user's local versions.
=> Remove old trade log

.github/workflows/PR-Push-test.yml
Since Github Actions uses a different timezone, it sometimes won't pass tests, so we're changing to our timezone.
=> Change timezone for Github Actions

cli/print_utils.py, test/stats/stats_test_utils.py
Removes the "UNABLE TO COMPUTE SHARPE RATIO" and all other irrelevant warning and info messages when testing. Still shows error messages.
=> Quiet Tests

modules/output/__init__.py, modules/output/equity_plot.py, modules/output/plots.py, modules/output/results.py
Added a trace to the equity plot tracking the average market change for all coins 
The computation of the average starting capital assumes an equal division between all coins. This will need to be refactored once we allow users to specify how to allocate the funds.
Might be good to add (if not already the case) in the docs that plotly allows the traces to be toggled by clicking on their respective legends
=> Add average market change line to equity plot

modules/output/plots.py
Fixes error that happens when coins had perceding nan values (e.g. they weren't online yet at the start of the backtesting period) which resulted in the avg market change line in the equity plot being nan as well.
=> Fix Avg Market Change Plot - Nan values

resources/setup/strategies/my_strategy.py, resources/setup/strategies/my_strategy_advanced.py
Adds qtpylib imports to standard strategy files. Is needed for some indicators, and it's neater if we already include it in the imports.
This does mean that there are two unused imports added - Codacy is likely going to complain about this, this can be safely ignored.
=> [Feat] Add qtpylib

modules/setup/config/validations.py
When coinpairs aren't configured correctly, for example the division symbol (/) is not used, or the pairs are not encapsulated in quotes, ugly errors were thrown. Now, a pretty error message is shown, and the engine exits gracefully.
=> [Fix] Proper error on "pairs not configured"

backtest_runner.py, backtesting/strategy.py
Now catches the error that is thrown when the loss function isn't implemented, and urges the user to look at the docs if they are unsure what to do with the loss function.
=> [Fix] Gracefully fail when loss function isn't implemented

.github/workflows/build_executables_mac.yml, .github/workflows/build_executables_windows.yml
The max build time for both windows and mac executable was set to 10 minutes. Lately we keep having builds fail because they hit that 10 minute mark. This PR increases that to 15 minutes - so builds that take just above 10 minutes don't fail and we don't have to rerun as many jobs.
=> [Fix] Increase max build time for windows and mac executable

.github/CODEOWNERS
Removes the codeowner files so Tijs doesn't get asked to review PR's for the Engine anymore.
=> [Fix] Remove Codeowners

backtest_runner.py, backtesting/strategy.py, modules/algo/backtesting.py, modules/setup/config/__init__.py, modules/stats/tradingmodule.py, resources/setup/strategies/my_strategy.py, resources/setup/strategies/my_strategy_advanced.py, test/stats/stats_test_utils.py, test/stats/test_main_results.py
Adds a cooldown function in the strategy file that can be used to implement custom cooldowns on separate trade sell reasons.
=> [Feat] Add buy cooldown

modules/output/results.py, modules/public/trading_stats.py, modules/stats/metrics/trades.py, modules/stats/stats.py, modules/stats/trade.py, modules/stats/tradingmodule.py, test/stats/test_coin_insights.py, test/stats/test_main_results.py
Moves the best, median, and trade ratios from the trade info table to the coin performance table, giving the same info at a coin-level rather than global level. Also allows to view those rankings on a relative return base and absolute return base
=> [Feat] Better trade overview

modules/setup/config/__init__.py
If a config file couldn't be found, the error message was supposed to print the path it was looking for. This is fixed by giving a different message if the path is None (happens if the user doesn't use the '-c' flag to point to a specific config file).
=> [Fix] missing config file path

main.py
On Python 3.10, asyncio would raise a DeprecationWarning. This has been fixed for 3.10 and 3.9.
Needs testing on other versions before merging.
=> [ENG-53] Asyncio DeprecationWarning

.github/.git-template/prepare-commit-msg, cli/print_utils.py
Makes available as a template a bash script that prepends the JIRA key at the start of the branch name in all commit messages automatically.
=> [ENG-63] Prepend JIRA key to commit message automatically
